runtime: python311
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: 'CHANGE-THIS-TO-RANDOM-SECRET-KEY'
  BASE_URL: 'https://YOUR-PROJECT-ID.uc.r.appspot.com'
  OAUTHLIB_INSECURE_TRANSPORT: '0'
  # Add your API keys here:
  # OPENAI_API_KEY: 'your-openai-api-key-here'
  # GOOGLE_CLIENT_ID: 'your-google-client-id'
  # GOOGLE_CLIENT_SECRET: 'your-google-client-secret'
  # FITBIT_CLIENT_ID: 'your-fitbit-client-id'
  # FITBIT_CLIENT_SECRET: 'your-fitbit-client-secret'

handlers:
- url: /static
  static_dir: static
  secure: always
  
- url: /.*
  script: auto
  secure: always
