runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: 'your-secret-key-here'
  # OPENAI_API_KEY: 'your-openai-api-key-here'

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
